### ISSUE TITLE
Couldn't save the position of the circle in uitableview

### ISSUE THREAD

**Issue by khanxc** [MedvedevMax/MMSegmentSlider#1]
On placing MMSegment on a uitableview, I could save the state of the value changed but not the position of the circle, refer screenshot
![screen shot 2016-08-26 at 5 38 41 pm](https://cloud.githubusercontent.com/assets/5825355/18004857/37e3af82-6bb4-11e6-9e10-60a49bbf9b0c.png)
The selected value is Sometime, but the position of the circle is at NO. How to solve this ? This happens when I scroll the uitableview up or down

**Comment by craftedbymax** [comment]
@khanxc, sorry for waiting, the issue is fixed.
Thank you.

**Comment by khanxc** [comment]
@MedvedevMax  No probs! Thank you!
